export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SEARCH_QUERY = "SEARCH_QUERY";
export const FILTER_PRODUCT = "FILTER_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_CHANGE_QUANTITY = "ADD_TO_CART_CHANGE_QUANTITY";
export const REMOVE_TO_CART = "REMOVE_TO_CART";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
